---
# tasks file for role1

- name: Copy local file to remote
  sudo: true
  copy:
    src: vars.yml
    dest: "{{ dest_proj_path }}/config/ansible/vars.yml"

- name: Create LUN
  na_cdot_lun:
    state: present
    name: ansibleLUN
    flexvol_name: ansibleVolume
    vserver: ansibleVServer
    size: 5
    size_unit: mb
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
   
   
- name: Create QTree
  na_cdot_qtree:
    state: present
    name: ansibleQTree
    flexvol_name: ansibleVolume
    vserver: ansibleVServer
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"

- name: Create SVM
  na_cdot_svm:
    state: present
    name: ansibleVServer
    root_volume: vol1
    root_volume_aggregate: aggr1
    root_volume_security_style: mixed
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
